# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dubbizle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dubbizle
  
  pod 'SwiftRangeSlider'
  
  platform :ios, '9.0'
  
  target 'DubbizleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DubbizleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
